### ISSUE TITLE
Edit toon color ramp selected by material

### ISSUE THREAD

**Issue by tomasadam3** [ScanMountGoat/xc3_lib#15]
When replacing certain model textures, such as Mythra's hair textures, the in-game shader effects will "blend" the color of the new texture with the color it was originally designed to accent. The ability to edit these materials should hopefully improve the look of certain texture replacements in-game.   

Massive Melee Mythra's (Right) hair texture replaced with with Pyra-Style Mythra's (Left)
![Untitled2](https://github.com/ScanMountGoat/xc3_lib/assets/42417617/9af4e1ce-56fe-43fb-9114-6acdcdf22a99)

Sword Fighter Class jacket textures replaced with Noah's Color 2 jacket textures (Noah's Color 2 Outfit used for Comparison)
![Untitled3](https://github.com/ScanMountGoat/xc3_lib/assets/42417617/c36c3e97-d93a-4853-a651-d940c66cb1fc)

**Comment by ScanMountGoat** [comment]
The color shifts on Noah's jacket are caused by the color ramps selected by the jacket material to use in the toon shading pass. The jacket basically has dark red lighting applied. I'm not sure about the cause for Mythra's hair.

There's still a bit of work that needs to be done on xc3_wgpu and xc3_viewer to understand what the material parameters actually do. Material edits will be possible once model rebuilding in xc3_model includes materials (hopefully 0.6.0). The easiest way to make material edits will be with a short Python script and xc3_model_py once the changes get ported to the Python bindings. I would add example scripts for people to use as a reference.

**Comment by tomasadam3** [comment]
Interesting, thanks for the insight.

I know it's just conjecture on my part, but I still feel like the Mythra hair issue has to be caused by something in the .wimdo no? Even if it's not caused by the material "hikari_hair_NEW2," each of Mythra's different models always seems to know which color/shading effects are supposed to applied to them in-game: Yellow for Base Mythra, Massive Melee Mythra, and Radiant Beach Mythra, Red for Pyra-Style Mythra, Purple for Carbon Mythra, and surprisingly, nothing for Hotsprings Mythra from what I've been able to see (replaced hair textures have no effects applied to them in-game).

Another character model of note is Base Pyra, as hair texture replacements also have no effect applied on them:
[Blue Sky Pyra](https://cdn.discordapp.com/attachments/1057429193958379570/1057862083552755762/2018092322350600-659B13F48903294AE2B3FA4F12DA9898.jpg?ex=65d6bed6&is=65c449d6&hm=7c19022add0417be95a683cc0b22a7c39d16272c34ece59cc6ceae006fbe8816&)
[Base Pyra with Blue Sky Pyra's green hair texture](https://cdn.discordapp.com/attachments/1057429193958379570/1057862083947024485/2022122822103900-659B13F48903294AE2B3FA4F12DA9898.jpg?ex=65d6bed6&is=65c449d6&hm=ddf870e077c0f45ed90d8c224cd46a92519756d3bea01cfbd00672c68fbc1e01&)

So either the hair materials for some models are programmed without any color/shading effects, or it's just something else entirely (which is probably the more likely answer). 

Don't know if any of this information will be helpful to you but I thought I'd at least share the results of tests I've done for over a year now (back when 3096's Ether Furnace was the only public texture replacement tool)

**Comment by ScanMountGoat** [comment]
The color shifts you're seeing on Massive Melee Mythra are also caused by the toon shading lighting gradients. This is just the lighting gradients for Massive Melee Mythra, default Rex, and default Pyra. 
![image](https://github.com/ScanMountGoat/xc3_lib/assets/23301691/085ff230-b596-4a28-ac03-c0ca6c993cc5)

This is with Mythra's hair set to Pyra's hair color. The hair effectively has yellow lighting applied.
![image](https://github.com/ScanMountGoat/xc3_lib/assets/23301691/191213e3-7550-462f-b99b-e09401c260bf)

Material edits won't be available for a while, so I would recommend trying to apply the textures to one of Mythra's other costumes if the UVs are the same. The toon lighting color isn't 100% saturated, so it's technically possible to adjust the RGB gain of the Pyra inspired textures to look mostly correct with a lot of trial and error.

**Comment by tomasadam3** [comment]
Good to finally know the exact cause. 

I can definitely wait until material edits become available. My temporary solution though has always been to edit the hair texture hues in such a way that it still looks similar to the intended color even after the yellow lighting is applied:

[Pyra-Style Mythra](https://images.gamebanana.com/img/ss/mods/648a68d7bba73.jpg)
[Pyra-Style Massive Melee Mythra](https://images.gamebanana.com/img/ss/mods/648a68d7baba9.jpg) (with edited hair texture)

I think I adapted my MMM edits pretty well all things considering, but I do look forward to the day when material edits become a thing so I can make them look even more official (via edited lighting gradients and outlines).

As for your recommendation to apply to these textures to other Mythra models, while it would be helpful for making hair edits to Mythra's base design(s), it actually doesn't mesh well (no pun intended) with Massive Melee Mythra's textures as they don't have the mesh for the covered up chest window, or the special lighting effect for the stockings:

Carbon Mythra's Textures on Massive Melee Mythra
![2022122915241400-659B13F48903294AE2B3FA4F12DA9898](https://github.com/ScanMountGoat/xc3_lib/assets/42417617/755500bb-e633-4ab9-8f56-5723c2009202)

Massive Melee Mythra's Stocking Textures on Carbon Mythra
![2022122915252600-659B13F48903294AE2B3FA4F12DA9898](https://github.com/ScanMountGoat/xc3_lib/assets/42417617/01b52d20-acf0-427b-80d9-a0156fd011ee)

**Comment by ScanMountGoat** [comment]
The selected toon gradient can be edited on the latest xenoblade_blender release: https://github.com/ScanMountGoat/xenoblade_blender/releases/tag/v0.15.0.1
