### ISSUE TITLE
Extend xc3_tex to include wilay (LAHD) support

### ISSUE THREAD

**Issue by KenNZ23** [ScanMountGoat/xc3_lib#6]
The xc3_lib appears to already support reading and writing wilay (LAHD) textures. Extending the xc3_tex programme to include this support for this file format would enable users to more easily modify menu/UI images.

Currently I am unaware of any other programme that enables users to generate wilay textures - only ones that write them out to png (eg. XbTool). Therefore, there remains a need for someone to make such support accessible to modders.

**Comment by ScanMountGoat** [comment]
This would be a neat feature. The reason I don't have wilay support in xc3_tex yet is because wilay contain multiple images and a lot of additional data. I'll need to implement something slightly more complicated than dragging and dropping a DDS to convert to wilay.

**Comment by ScanMountGoat** [comment]
This is implemented now as part of xc3_tex and will be part of the upcoming 0.3.0 release. xc3_tex will support exporting and updating images in existing wilay files.

**Comment by KenNZ23** [comment]
Awesome! Thanks so much for implementing this. I look forward to testing this in the future.
If you feel like it, would you mind commenting on the wilay format some more? I've only used XbTool which only works on images in the 'menu/image' directory, outputting PNG's, presumably due to transparency and being lossless. I'm picking you're using DDS to handle transparency etc, but I note your code mentions them containing jpeg files as well. It also looks like you may have updated your code (at least in xc3_tex) to handle the lagp variant of the wilay format?
I'm curious to learn more if you don't mind sharing some of your knowledge.

**Comment by ScanMountGoat** [comment]
The wilay files use compressed Mibl (LIBM magic) images just like models and maps. I use DDS since it can preserve all the compressed texture data. Some of the wilay files also have embedded JPEG files. The LAGP magic files have an almost identical structure to the LAHD magic files. You can find the code linked on the readme. My focus right now is just on rebuilding the files rather than figuring out what the other fields do, so I can't really explain any more than that.
